[build]
  command = "npm install && npx vite build --config vite.config.prod.ts"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200